# Generated by Django 3.2.3 on 2021-05-22 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_auto_20210523_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist_songs',
            name='music_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api_basic.musics'),
        ),
        migrations.AlterField(
            model_name='playlist_songs',
            name='playlist_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api_basic.playlists'),
            preserve_default=False,
        ),
    ]
