# Generated by Django 3.2.3 on 2021-05-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_auto_20210523_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist_songs',
            name='music_id',
        ),
        migrations.AddField(
            model_name='playlist_songs',
            name='music_id',
            field=models.ManyToManyField(to='api_basic.Musics'),
        ),
    ]
